# Summarize incidence

```
From: Curtis, Jeffrey R [mailto:jrcurtis@uabmc.edu] 
Sent: Thursday, May 11, 2017 10:59 AM
Subject: Table 1 Distribution of Characteristics of AS cohort by data source 1 year baseline

Here is table shell for table 1 for AS cohort. All covariates are measured in
baseline, although I think that we should have additional rows added for all
13 outcomes of interest, using all available leftward data (not just
baseline). So for example, someone who had history of uveitis, or cancer,
would appear as rows in this table.

This would be the same format for Aim II that provides the corresponding
information with each column representing the exposure episodes.
```

Read crude incidence data.
See `modelIncidenceOutcomes.sas`.

```{r}
df <-
  "../data/processed/crudeIncidence.csv" %>% 
  read.csv(file = ., na.string = c("NA", "")) %>% 
  rename(disease = Disease) %>% 
  mutate(type = ifelse(outcomeCategory %in% c("Inflammatory bowel disease", "PsO/PsA", "Uveitis"),
                       "Disease manifestation",
                       "Comorbidity"))
df %>% 
  group_by(database, exposure) %>% 
  summarize(nPatid = max(nPatid)) %>% 
  kable()
```

\newline

```{r}
df %>% 
  select(c(type, outcomeCategory, disease)) %>% 
  unique() %>% 
  kable()
```

Table of **incidence per 100 person-years**

```{r}
foo <- function(db, exp) {
    scale <- 100
    df %>% 
      filter(database == db) %>% 
      filter(exposure == exp) %>%
      mutate(scale = scale) %>% 
      mutate(incidenceRate = nEvents / personYears * scale) %>% 
      mutate(lower = incCI(nEvents, personYears)[, "lower"] * scale,
             upper = incCI(nEvents, personYears)[, "upper"] * scale) %>% 
      select(c(database, exposure, type, outcomeCategory, disease, nPatid, nEvents, personYears, scale, incidenceRate, lower, upper)) %>% 
      select(-c(nPatid, nEvents, personYears, scale))
}
df1a <- foo("MPCD", "TNF")
df1b <- foo("MPCD", "DMARD")
df1c <- foo("MPCD", "NSAID or no exposure")
df2a <- foo("Marketscan", "TNF")
df2b <- foo("Marketscan", "DMARD")
df2c <- foo("Marketscan", "NSAID or no exposure")
df3a <- foo("Medicare", "TNF")
df3b <- foo("Medicare", "DMARD")
df3c <- foo("Medicare", "NSAID or no exposure")
by <- c("database", "type", "outcomeCategory", "disease")
fmt <- "%.02f (%.02f-%.02f)"
foo <- function (a, b, c) {
    merge(a %>% select(-exposure), 
          merge(b %>% select(-exposure), 
                c %>% select(-exposure), 
                by = by, all = TRUE, suffixes = c("_DMARD", "_NSAIDNoExp")), 
          by = by, all = TRUE) %>% 
    rename(incidenceRate_TNF = incidenceRate,
           lower_TNF = lower,
           upper_TNF = upper) %>% 
    select(-c(database))
}
incidence <- 
  merge(foo(df1a, df1b, df1c), 
        merge(foo(df2a, df2b, df2c),
              foo(df3a, df3b, df3c),
              by = c("type", "outcomeCategory", "disease"),
              all = TRUE,
              suffixes = c("_Marketscan", "_Medicare")),
        by = c("type", "outcomeCategory", "disease"),
        all = TRUE) %>% 
  rename(incidenceRate_NSAIDNoExp_MPCD = incidenceRate_NSAIDNoExp,
         lower_NSAIDNoExp_MPCD = lower_NSAIDNoExp,
         upper_NSAIDNoExp_MPCD = upper_NSAIDNoExp,
         incidenceRate_DMARD_MPCD = incidenceRate_DMARD,
         lower_DMARD_MPCD = lower_DMARD,
         upper_DMARD_MPCD = upper_DMARD,
         incidenceRate_TNF_MPCD = incidenceRate_TNF,
         lower_TNF_MPCD = lower_TNF,
         upper_TNF_MPCD = upper_TNF) %>%
  select(matches("type|outcomeCategory|disease|incidence|lower|upper")) %>% 
  mutate(incidenceRate_NSAIDNoExp_MPCD = ifelse(is.na(incidenceRate_NSAIDNoExp_MPCD), "0", sprintf(fmt, incidenceRate_NSAIDNoExp_MPCD, lower_NSAIDNoExp_MPCD, upper_NSAIDNoExp_MPCD)),
         incidenceRate_NSAIDNoExp_Marketscan = ifelse(is.na(incidenceRate_NSAIDNoExp_Marketscan), "0", sprintf(fmt, incidenceRate_NSAIDNoExp_Marketscan, lower_NSAIDNoExp_Marketscan, upper_NSAIDNoExp_Marketscan)),
         incidenceRate_NSAIDNoExp_Medicare = ifelse(is.na(incidenceRate_NSAIDNoExp_Medicare), "0", sprintf(fmt, incidenceRate_NSAIDNoExp_Medicare, lower_NSAIDNoExp_Medicare, upper_NSAIDNoExp_Medicare)),
         incidenceRate_DMARD_MPCD = ifelse(is.na(incidenceRate_DMARD_MPCD), "0", sprintf(fmt, incidenceRate_DMARD_MPCD, lower_DMARD_MPCD, upper_DMARD_MPCD)),
         incidenceRate_DMARD_Marketscan = ifelse(is.na(incidenceRate_DMARD_Marketscan), "0", sprintf(fmt, incidenceRate_DMARD_Marketscan, lower_DMARD_Marketscan, upper_DMARD_Marketscan)),
         incidenceRate_DMARD_Medicare = ifelse(is.na(incidenceRate_DMARD_Medicare), "0", sprintf(fmt, incidenceRate_DMARD_Medicare, lower_DMARD_Medicare, upper_DMARD_Medicare)),
         incidenceRate_TNF_MPCD = ifelse(is.na(incidenceRate_TNF_MPCD), "0", sprintf(fmt, incidenceRate_TNF_MPCD, lower_TNF_MPCD, upper_TNF_MPCD)),
         incidenceRate_TNF_Marketscan = ifelse(is.na(incidenceRate_TNF_Marketscan), "0", sprintf(fmt, incidenceRate_TNF_Marketscan, lower_TNF_Marketscan, upper_TNF_Marketscan)),
         incidenceRate_TNF_Medicare = ifelse(is.na(incidenceRate_TNF_Medicare), "0", sprintf(fmt, incidenceRate_TNF_Medicare, lower_TNF_Medicare, upper_TNF_Medicare))) %>% 
  rename("MPCD NSAID or no exposure" = incidenceRate_NSAIDNoExp_MPCD,
         "MPCD DMARD" = incidenceRate_DMARD_MPCD,
         "MPCD TNF" = incidenceRate_TNF_MPCD,
         "Marketscan NSAID or no exposure" = incidenceRate_NSAIDNoExp_Marketscan,
         "Marketscan DMARD" = incidenceRate_DMARD_Marketscan,
         "Marketscan TNF" = incidenceRate_TNF_Marketscan,
         "Medicare NSAID or no exposure" = incidenceRate_NSAIDNoExp_Medicare,
         "Medicare DMARD" = incidenceRate_DMARD_Medicare,
         "Medicare TNF" = incidenceRate_TNF_Medicare) %>% 
  select(-matches("lower|upper"))
incidence %>% kable()
incidence %>% write.csv(file = "../data/processed/incidence.csv", row.names = FALSE)
```


## TNF vs NSAID or no exposure

```{r}
dfLong <- bind_rows(df1a, df1c, df2a, df2c, df3a, df3c)
set1 <- c("Disease manifestation")
set2 <- c("Hematologic Cancer",
          "Non Melanoma Skin Cancer",
          "Solid Cancer",
          "Aortic Insufficiency/Aortic Regurgitation",
          "Conduction Block",
          "Myocardial infarction",
          "Hospitalized infection",
          "Opportunistic infection",
          "Amyloidosis")
set3 <-c("IgA nephropathy",
         "Nephrotic syndrome",
         "Apical Pulmonary fibrosis",
         "Interstitial lung disease",
         "Restrictive lung disease",
         "Cauda Equina syndrome",
         "Spinal Cord compression",
         "Clinical vertebral fracture",
         "Non-vertebral osteoporotic fracture")
dfLong %>% 
  filter(type == set1) %>% 
  plotIncidence(filename = "incidenceTNFvsNSAID_1")
dfLong %>% 
  filter(disease %in% set2) %>% 
  plotIncidence(filename = "incidenceTNFvsNSAID_2")
dfLong %>% 
  filter(disease %in% set3 | outcomeCategory == "Lung disease") %>% 
  plotIncidence(filename = "incidenceTNFvsNSAID_3")
```


## **TNF** versus **NSAID or no exposure**

**MPCD**

```{r, eval = FALSE}
exp <- c("TNF", "NSAID or no exposure")
digits <- c(rep(0, 4), 1, 1, 3)
bindCompare("MPCD", exp) %>% kable(digits = digits)
```

**Marketscan**

```{r, eval = FALSE}
bindCompare("Marketscan", exp) %>% kable(digits = digits)
```

**Medicare**

```{r, eval = FALSE}
bindCompare("Medicare", exp) %>% kable(digits = digits)
```

## **TNF** versus **DMARD**

**MPCD**

```{r, eval = FALSE}
exp <- c("TNF", "DMARD")
bindCompare("MPCD", exp) %>% kable(digits = digits)
```

**Marketscan**

```{r, eval = FALSE}
bindCompare("Marketscan", exp) %>% kable(digits = digits)
```

**Medicare**

```{r, eval = FALSE}
bindCompare("Medicare", exp) %>% kable(digits = digits)
```
